### ISSUE TITLE
is there a mistake in the OriLinearGNN code?

### ISSUE THREAD

**Issue by chong-w** [LYuhang/GNN_Review#1]
GNN_Implement_with_Pytorch -> Linear GNN模型 ->  line175 :

H = torch.index_select(H, 0, X_Node)

it should be:

H = torch.index_select(H, 0, X_Neis)

**Comment by jonanhu** [comment]
I also think it should be X_Neis, because from the formula in the paper:
![image](https://user-images.githubusercontent.com/44963813/78518855-326dbe80-77f4-11ea-8f57-00f4648e814d.png)
 we can know that we should use the states of neighbors of the node

**Comment by LYuhang** [comment]
Thank you for pointing out this error. Just as @jonanhu said, it should be the states of the neighbor nodes, X_u. Thus, it should be (@chongwqqcom):
H = torch.index_select(H, 0, X_Neis)
I have fixed this error. Sorry for replying so late!
